# render.
services:
  - type: web
    name: rails
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        value: e3797695370b2eb6073dfea8621ca62fca06cf5b89a9964f38d84650c6e8b0f3e40220b5f500706dd978f33ee7dd608deda1e0abe063a91b238cc985ade91c33
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString


# databases:
#   - name: postgres
#     ipAllowList: []

# services:
#   - type: web
#     name: rails
#     env: ruby
#     plan: free
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: RAILS_MASTER_KEY
#         value: e3797695370b2eb6073dfea8621ca62fca06cf5b89a9964f38d84650c6e8b0f3e40220b5f500706dd978f33ee7dd608deda1e0abe063a91b238cc985ade91c33
#         sync: false
#       - key: DATABASE_URL
#         fromDatabase:
#           name: postgres
#           property: connectionString


# databases:
#   - name: postgres
#     ipAllowList: []

# services:
#   - type: web
#     name: rails
#     env: ruby
#     plan: free
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#      - key: RAILS_MASTER_KEY
#        sync: false
#      - key: DATABASE_URL
#        fromDatabase:
#         name: postgres
#         property: connectionString